<a href="https://colab.research.google.com/github/eduardozurek/ia/blob/main/_007_aprendizaje_supervisado/_008_clasificadores_bayesianos/09b_Bernoulli.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Ejemplo - Bernoulli - Clasificador Bayesiano Ingenuo - Naïve Bayes Classifier**

In [ ]:
import pandas as pd
url = "https://web.stanford.edu/~hastie/ElemStatLearn/datasets/spam.data"
datos = pd.read_csv(url,sep=' ',header=None)

In [ ]:
import numpy as np
datos = np.asarray(datos)
y = datos[:,-1]
X = datos[:,0:48]
print(y.shape)
print(X.shape)

(4601,)
(4601, 48)

In [ ]:
import pandas as pd
df = pd.DataFrame(X)
df

,0,1,2,3,4,5,6,7,8,9,...,38,39,40,41,42,43,44,45,46,47
0,0.00,0.64,0.64,0.0,0.32,0.00,0.00,0.00,0.00,0.00,...,0.0,0.00,0.0,0.0,0.00,0.00,0.00,0.00,0.0,0.0
1,0.21,0.28,0.50,0.0,0.14,0.28,0.21,0.07,0.00,0.94,...,0.0,0.00,0.0,0.0,0.00,0.00,0.00,0.00,0.0,0.0
2,0.06,0.00,0.71,0.0,1.23,0.19,0.19,0.12,0.64,0.25,...,0.0,0.06,0.0,0.0,0.12,0.00,0.06,0.06,0.0,0.0
3,0.00,0.00,0.00,0.0,0.63,0.00,0.31,0.63,0.31,0.63,...,0.0,0.00,0.0,0.0,0.00,0.00,0.00,0.00,0.0,0.0
4,0.00,0.00,0.00,0.0,0.63,0.00,0.31,0.63,0.31,0.63,...,0.0,0.00,0.0,0.0,0.00,0.00,0.00,0.00,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4596,0.31,0.00,0.62,0.0,0.00,0.31,0.00,0.00,0.00,0.00,...,0.0,0.00,0.0,0.0,0.00,0.31,0.31,0.31,0.0,0.0
4597,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.00,...,0.0,0.00,0.0,0.0,0.00,0.00,0.00,2.00,0.0,0.0
4598,0.30,0.00,0.30,0.0,0.00,0.00,0.00,0.00,0.00,0.00,...,0.0,0.00,0.0,0.0,0.00,0.00,0.00,1.20,0.0,0.0
4599,0.96,0.00,0.00,0.0,0.32,0.00,0.00,0.00,0.00,0.00,...,0.0,0.00,0.0,0.0,0.00,0.32,0.00,0.32,0.0,0.0
4600,0.00,0.00,0.65,0.0,0.00,0.00,0.00,0.00,0.00,0.00,...,0.0,0.00,0.0,0.0,0.00,0.00,1.97,0.65,0.0,0.0

In [ ]:
df.describe()

,0,1,2,3,4,5,6,7,8,9,...,38,39,40,41,42,43,44,45,46,47
count,4601.000000,4601.000000,4601.000000,4601.000000,4601.000000,4601.000000,4601.000000,4601.000000,4601.000000,4601.000000,...,4601.000000,4601.000000,4601.000000,4601.000000,4601.000000,4601.000000,4601.000000,4601.000000,4601.000000,4601.000000
mean,0.104553,0.213015,0.280656,0.065425,0.312223,0.095901,0.114208,0.105295,0.090067,0.239413,...,0.078629,0.064834,0.043667,0.132339,0.046099,0.079196,0.301224,0.179824,0.005444,0.031869
std,0.305358,1.290575,0.504143,1.395151,0.672513,0.273824,0.391441,0.401071,0.278616,0.644755,...,0.434672,0.349916,0.361205,0.766819,0.223812,0.621976,1.011687,0.911119,0.076274,0.285735
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,0.000000,0.000000,0.420000,0.000000,0.380000,0.000000,0.000000,0.000000,0.000000,0.160000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.110000,0.000000,0.000000,0.000000
max,4.540000,14.280000,5.100000,42.810000,10.000000,5.880000,7.270000,11.110000,5.260000,18.180000,...,11.110000,4.760000,7.140000,14.280000,3.570000,20.000000,21.420000,22.050000,2.170000,10.000000

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = \
    train_test_split(X, y, test_size=0.25, random_state=23)

In [ ]:
from sklearn.naive_bayes import BernoulliNB
# Con el umbral de binarización en cero
BerNB = BernoulliNB(binarize=0.4,fit_prior=True)
BerNB.fit(X_train,y_train)
y_esperado = y_test
y_predicho = BerNB.predict(X_test)

In [ ]:
from sklearn.metrics import accuracy_score, confusion_matrix, recall_score, precision_score
print(accuracy_score(y_esperado,y_predicho))
print(recall_score(y_esperado,y_predicho))
print(precision_score(y_esperado,y_predicho))
print(confusion_matrix(y_esperado,y_predicho))

0.894005212858384
0.8649789029535865
0.8760683760683761
[[619  58]
 [ 64 410]]

In [ ]:
from sklearn.naive_bayes import BernoulliNB
# Con el umbral de binarización en cero
BerNB = BernoulliNB(binarize=True,fit_prior=False)
BerNB.fit(X_train,y_train)
y_esperado = y_test
y_predicho = BerNB.predict(X_test)

In [ ]:
from sklearn.metrics import accuracy_score, confusion_matrix, recall_score, precision_score
print(accuracy_score(y_esperado,y_predicho))
print(recall_score(y_esperado,y_predicho))
print(precision_score(y_esperado,y_predicho))
print(confusion_matrix(y_esperado,y_predicho))

0.8279756733275413
0.8924050632911392
0.7421052631578947
[[530 147]
 [ 51 423]]

In [ ]:
# con el umbral de binarización mayor que cero
BerNB = BernoulliNB(binarize=0.5)
BerNB.fit(X_train,y_train)
y_esperado = y_test
y_predicho = BerNB.predict(X_test)
print(accuracy_score(y_esperado,y_predicho))

0.889661164205039

In [ ]:
# con el umbral de binarización mayor que cero
BerNB = BernoulliNB(binarize=0.1)
BerNB.fit(X_train,y_train)
y_esperado = y_test
y_predicho = BerNB.predict(X_test)
print(accuracy_score(y_esperado,y_predicho))

0.8801042571676803

In [ ]:
# con el umbral de binarización mayor que cero
BerNB = BernoulliNB(binarize=0.8)
BerNB.fit(X_train,y_train)
y_esperado = y_test
y_predicho = BerNB.predict(X_test)
print(accuracy_score(y_esperado,y_predicho))

0.8540399652476107